var ActorList = [
    'actor/player/ShipActor',
    'actor/player/DemoShipActor',
    'actor/enemy/EnemyActor',
    'actor/object/ChunkActor',
    'actor/object/BoomChunkActor',
    'actor/object/ExplosionActor',
    'actor/object/SmallExplosionActor',
    'actor/projectile/EmdProjectileActor',
    'actor/projectile/PlasmaProjectileActor',
    'actor/projectile/PlasmaBlastProjectileActor',
    'actor/projectile/PlasmaBlastMiniProjectileActor',
    'actor/projectile/LaserProjectileActor',
    'actor/projectile/RedLaserProjectileActor',
    'actor/projectile/RedLaserEnemyProjectileActor',
    'actor/projectile/PurpleLaserProjectileActor',
    'actor/projectile/GreenLaserProjectileActor',
    'actor/projectile/MoltenProjectileActor',
    'actor/projectile/RingProjectileActor',
    'actor/projectile/PulseWaveProjectileActor',
    'actor/projectile/ConcsnMissileActor',
    'actor/projectile/EnemyConcsnMissileActor',
    'actor/projectile/HomingMissileActor',
    'actor/projectile/EnemyHomingMissileActor',
    'actor/map/EnemySpawnerActor',
    'actor/map/EnemySpawnMarkerActor',
    'actor/map/ItemSpawnerActor',
    'actor/DebugActor',
    'actor/pickup/ShieldPickupActor',
    'actor/pickup/EnergyPickupActor',
    'actor/pickup/PlasmaPickupActor',
    'actor/pickup/MissileQuadPickupActor'
];

module.exports = ActorList;
