var ActorList = [
    'actor/player/ShipActor',
    'actor/enemy/MookActor',
    'actor/enemy/SniperActor',
    'actor/enemy/OrbotActor',
    'actor/enemy/ShulkActor',
    'actor/object/ChunkActor',
    'actor/object/BoomChunkActor',
    'actor/object/ExplosionActor',
    'actor/projectile/PlasmaProjectileActor',
    'actor/projectile/LaserProjectileActor',
    'actor/projectile/RedLaserProjectileActor',
    'actor/projectile/PurpleLaserProjectileActor',
    'actor/projectile/GreenLaserProjectileActor',
    'actor/projectile/MoltenProjectileActor',
    'actor/projectile/RingProjectileActor',
    'actor/projectile/PulseWaveProjectileActor',
    'actor/projectile/ConcsnMissileActor',
    'actor/map/MapActor',
    'actor/map/EnemySpawnerActor',
    'actor/map/EnemySpawnMarkerActor',
    'actor/map/ItemSpawnerActor',
    'actor/DebugActor',
    'actor/pickup/ShieldPickupActor',
    'actor/pickup/EnergyPickupActor',
    'actor/pickup/PlasmaPickupActor',
    'actor/pickup/MissileQuadPickupActor'
];

module.exports = ActorList;
