module.exports = [
    {
        strafeLeft: 'a',
        strafeRight: 'd',
        forward: 'w',
        backward: 's',
        rotateLeft: 'mouseX',
        rotateRight: 'mouseX',
        fireWeapon1: 'mouseLeft',
        fireWeapon2: 'mouseRight',
        swapWeapon1: 'q',
        swapWeapon2: 'e',
        targetingLonger: 'mouseY',
        targetingShorter: 'mouseY',
        viewHigher: 'mouseScroll',
        viewLower: 'mouseScroll'
    },
    {
        strafeLeft: 'a',
        strafeRight: 'd',
        forward: 'w',
        backward: 's',
        rotateLeft: 'left',
        rotateRight: 'right',
        fireWeapon1: 'shiftLeft',
        fireWeapon2: 'space',
        swapWeapon1: 'q',
        swapWeapon2: 'e',
        targetingLonger: 'o',
        targetingShorter: 'p',
        viewHigher: 'up',
        viewLower: 'down'
    },
    {
        strafeLeft: 'a',
        strafeRight: 'd',
        forward: 'up',
        backward: 'down',
        rotateLeft: 'left',
        rotateRight: 'right',
        fireWeapon1: 's',
        fireWeapon2: 'space',
        swapWeapon1: 'q',
        swapWeapon2: 'e',
        targetingLonger: 'o',
        targetingShorter: 'p',
        viewHigher: 'w',
        viewLower: 'x'
    }];